#!/usr/bin/env bash

# To find commands using a shortcut you can use: gsettings list-schemas | grep keybinding | while read SCHEMA; do   gsettings list-keys $SCHEMA | while read KEY; do     echo -ne "$KEY\t$SCHEMA\t";     gsettings get $SCHEMA $KEY;   done; done | grep '<Super>Up'
gsettings set org.gnome.desktop.wm.keybindings maximize "[]" || exit $EXIT_UNEXPECTED
gsettings set org.gnome.shell.keybindings toggle-overview "['<Super>Space', '<Super>Up']" || exit $EXIT_UNEXPECTED
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-left "['<Super>Left']" || exit $EXIT_UNEXPECTED
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-right "['<Super>Right']" || exit $EXIT_UNEXPECTED
gsettings set org.gnome.mutter.keybindings toggle-tiled-right "['<Super><Alt>Right']" || exit $EXIT_UNEXPECTED
gsettings set org.gnome.mutter.keybindings toggle-tiled-left "['<Super><Alt>Left']" || exit $EXIT_UNEXPECTED
