#!/usr/bin/env bash

# To find commands using a shortcut you can use: gsettings list-schemas | grep keybinding | while read SCHEMA; do   gsettings list-keys $SCHEMA | while read KEY; do     echo -ne "$KEY\t$SCHEMA\t";     gsettings get $SCHEMA $KEY;   done; done | grep '<Super>Up'
compose step "Rebind conflicting keys"
gsettings set org.gnome.desktop.wm.keybindings maximize "[]" || exit $EXIT_UNEXPECTED
gsettings set org.gnome.mutter.keybindings toggle-tiled-right "['<Super><Alt>Right']" || exit $EXIT_UNEXPECTED
gsettings set org.gnome.mutter.keybindings toggle-tiled-left "['<Super><Alt>Left']" || exit $EXIT_UNEXPECTED

compose step "Bind control center shortcuts"
gsettings set org.gnome.shell.keybindings toggle-overview "['<Super>Space', '<Super>Up']" || exit $EXIT_UNEXPECTED

compose step "Bind workspace shortcuts"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-left "['<Super>Left']" || exit $EXIT_UNEXPECTED
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-right "['<Super>Right']" || exit $EXIT_UNEXPECTED

compose step "Remap capslock to escape"
gsettings set org.gnome.desktop.input-sources xkb-options "['caps:escape']"

compose step "Map Brightness to (super+F7/F8) keys"
gsettings set org.gnome.settings-daemon.plugins.media-keys custom-keybindings "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/brightness-up/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/brightness-down/']"
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/brightness-down/ command 'gdbus call --session --dest org.gnome.SettingsDaemon.Power --object-path /org/gnome/SettingsDaemon/Power --method org.gnome.SettingsDaemon.Power.Screen.StepDown'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/brightness-up/ command 'gdbus call --session --dest org.gnome.SettingsDaemon.Power --object-path /org/gnome/SettingsDaemon/Power --method org.gnome.SettingsDaemon.Power.Screen.StepUp'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/brightness-down/ binding '<Super>F7'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/brightness-up/ binding '<Super>F8'
