#!/usr/bin/env bash

case "$1" in
    "help" | "--help" | "-h" | "")
        mdf "Setup encryption on a specified drive";
        mdf ">> This will FORMAT the drive, erasing its contents!"
        mdf "Usage: encrypt-drive [drive] ([mount-target])";
        mdf "    [drive] - The partition path to encrypt (eg. /dev/sda1)"
        mdf "    [mount-target] - A mount-point to initialize the drive on after complete (eg. /media/example) (optional)"
        exit 0;
    ;;
esac

DRIVE=$1;

if [ "$DRIVE" == "" ]; then
    mdf ">>> Drive argument required (eg. /dev/sda1)"
    exit $EXIT_ILLEGAL_ARG;
fi

mdf "# Encrypting $DRIVE"

# Encrypt the partition
sudo cryptsetup luksFormat $DRIVE

# Unlock Partition
read -p "Mapper Label (eg. 'media', 'data'): " DM
if [ "$DM" == "" ]; then
    mdf ">>> DM argument required"
    exit $EXIT_ILLEGAL_ARG;
fi
sudo cryptsetup luksOpen $DRIVE $DM

# Format the encrypted partition via diskmapper
sudo mkfs.ext4 /dev/mapper/$DM

TARGET=$2
if [ "$TARGET" != "" ]; then
    sudo mkdir -p $TARGET
    sudo mount $DM $TARGET
fi
