#!/usr/bin/env bash

case "$1" in
    "help" | "--help" | "-h" | "")
        echo "Scales the display";
        echo "Usage: scale-display [SCALE]";
        exit 0;
    ;;
esac

SCALE=$1;

if [ "$SCALE" == "" ]; then
    compose error "Scaling argument required"
    exit $EXIT_ILLEGAL_ARG;
fi

if assert-system os linux; then
    gsettings set org.gnome.desktop.interface text-scaling-factor $SCALE
else
    compose error "OS Unsupported"
    exit $EXIT_ILLEGAL_STATE
fi
