#!/usr/bin/env bash

BIN_NAME=$1
BIN_PATH="$ASSETS_HOME/Software/$BIN_NAME"
SIG_PATH="$ASSETS_HOME/Software/$BIN_NAME.sig"

if [ ! -f $BIN_PATH ]; then
    echo "No Bin found at $BIN_PATH"
    exit $EXIT_ILLEGAL_ARG
fi

if [ ! -f $SIG_PATH ]; then
    echo "No signature found at $SIG_PATH"
    exit $EXIT_ILLEGAL_ARG
fi

compose h1 "Installing $BIN_NAME"

compose step "Verifying App Signature"
if ! gpg --verify $SIG_PATH $BIN_PATH; then
    echo "Failed signature check"
    exit 2
fi

compose step "Copying Binary"
cp $BIN_PATH $BIN_HOME

compose success "Installed"
