#!/usr/bin/env bash

style=$1
shift

case $style in
    "h1")
        echo -e "\\033[1m# $@\\033[0m";
        ;;
    "h2")
        echo -e "\\033[01;34m## $@\\033[0m";
        ;;
    "h3")
        echo -e "\\033[0;34m### $@\\033[0m";
        ;;
    "success")
        echo -e "\\033[32m$@\\033[0m"
        ;;
    "error")
        echo -e "\\033[31m$@\\033[0m" 1>&2;
        ;;
    "warning" | "warn")
        echo -e "\\033[33m$@\\033[0m" 1>&2;
        ;;
    "step" | "li")
        echo -e " - $@"
        ;;
    "space" | "spacer")
        echo ""
        ;;
    "hr")
        printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' -
        ;;
    *)
        echo "$@"
    ;;
esac
