#!/usr/bin/env bash

mdf "# Garbage collector";

mdf "## Removing Downloads older than 3 days";
find ~/Downloads -mindepth 1 -name "*" -ctime +3 -print -exec trash "{}" \;


if [ -d $HOME/Desktop ]; then
    mdf "## Removing Desktop Junk";
    find ~/Desktop -mindepth 1 -name "*" -print -exec trash "{}" \;
fi

mdf "++ Success"