#!/usr/bin/env bash

case "$1" in
    "help" | "--help" | "-h" | "")
        mdf "Replaces a target file with a link, trashing any existing file.";
        mdf "> Usage: re-link [SOURCE] [DESTINATION]";
        exit 0;
    ;;
esac

SOURCE=$1;
DESTINATION=$2;

if [ ! -f $SOURCE ]; then
    mdf ">>> Source not found: $SOURCE";
    exit $EXIT_ILLEGAL_ARG;
fi

if [ -f "$DESTINATION" ] || [ -L "$DESTINATION" ]; then
    mdf " - Removing old source: $DESTINATION";
    trash $DESTINATION;
fi

mdf " - Linking $DESTINATION -> $SOURCE";
ln -s $SOURCE $DESTINATION;
