#!/usr/bin/env bash

mdf "# Running System Updates"

if assert-system has-command softwareupdate; then
    mdf "## OS Native Software"
    softwareupdate -i -a || exit $EXIT_UNEXPECTED
fi

if assert-system has-command dnf; then
    mdf "## Updating DNF"
    sudo dnf update || exit $EXIT_UNEXPECTED
fi

if assert-system has-command rpm-ostree; then
    mdf "## Installing ostree updates"
    sudo rpm-ostree upgrade || $EXIT_UNEXPECTED
fi

if assert-system has-command brew; then
    mdf "## Updating HomeBrew"
    brew update && brew upgrade && brew cleanup || exit $EXIT_UNEXPECTED
fi

if assert-system has-command npm && assert-system has-command node; then
    mdf "## Updating NPM"
    sudo npm install npm -g && sudo npm update -g || exit $EXIT_UNEXPECTED
fi

if assert-system has-command snap; then
    mdf "## Updating Snap"
    sudo snap refresh || exit $EXIT_UNEXPECTED
fi

if assert-system has-command flatpak; then
    mdf "## Updating Flatpak"
    flatpak update -y || exit $EXIT_UNEXPECTED
fi

mdf "## Updating bin applications"
find $BIN_HOME -mindepth 1 -name "*" -print -exec sh -c '\
if [ -f "$ASSETS_HOME/Software/$(basename {})" ]; then \
app-install $(basename {}); \
else mdf "> No Asset file. Skipping"; \
fi' \;

mdf "## Updating Libs"
cd $LIB_HOME
    git pull --ff-only --verify-signatures https://github.com/ReneeVandervelde/system-lib.git master
cd -

mdf "++ All Updates Complete"
