#!/usr/bin/env bash

function __status {
    if [ ! -f /etc/yum.repos.d/resilio-sync.repo ]; then
        exit 2
    fi
}

function __configure {
    sudo cp $LIB_SRC_ROOT/rhel/resources/resilio-sync.repo /etc/yum.repos.d/

    if assert-system has-command rpm-ostree; then
        sudo rpm-ostree install resilio-sync
        mdf "> Reboot required"
    else if assert-system has-command dnf; then
        sudo dnf install resilio-sync
        mdf "+ Configured"
    else
        mdf ">>> Unsupported OS"
        exit $EXIT_ILLEGAL_STATE
    fi
}

command=$1;
shift

case $command in
    "status")
        __status $@
    ;;
    "configure")
        __configure $@
    ;;
    *)
        exit $EXIT_ILLEGAL_ARG
    ;;
esac
