#!/usr/bin/env bash

CERTFILE=$HOME/sync.key
KEYFILE=$HOME/sync.crt

if [ ! -f $CERTFILE ] || [ ! -f $KEYFILE ]; then
    compose error "Script requires a cert+key pair uploaded to the home directory. Expected files at:"
    compose li $CERTFILE
    compose li $KEYFILE
    exit $EXIT_ILLEGAL_ARG
fi

configure-sync || $EXIT_UNEXPECTED

compose h2 "Stopping Service for reconfigure"
sudo systemctl stop resilio-sync.service || exit $EXIT_UNEXPECTED

compose h1 "Configuring Sync Server"
sudo cp $LIB_SRC_ROOT/rhel/resources/sync-server.json /etc/resilio-sync/config.json || exit $EXIT_UNEXPECTED;
sudo mv $KEYFILE /var/lib/resilio-sync/ || exit $EXIT_UNEXPECTED;
sudo mv $CERTFILE /var/lib/resilio-sync/ || exit $EXIT_UNEXPECTED;
sudo firewall-cmd --permanent --add-port=8888/tcp  || exit $EXIT_UNEXPECTED;
sudo firewall-cmd --permanent --add-port=34034/tcp  || exit $EXIT_UNEXPECTED;
sudo firewall-cmd --permanent --add-port=34034/udp  || exit $EXIT_UNEXPECTED;
sudo firewall-cmd --permanent --add-port=3838/udp  || exit $EXIT_UNEXPECTED;
sudo firewall-cmd --permanent --add-port=1900/udp  || exit $EXIT_UNEXPECTED;
sudo firewall-cmd --permanent --add-port=5351/udp  || exit $EXIT_UNEXPECTED;
sudo service firewalld restart || exit $EXIT_UNEXPECTED;

compose h2 "Re-starting Service"
sudo systemctl start resilio-sync.service || exit $EXIT_UNEXPECTED
 
 compose success "Successfully configured Sync server"
