#!/usr/bin/env bash

compose h1 "Configuring DNF Repo"
sudo cp $LIB_SRC_ROOT/rhel/resources/resilio-sync.repo /etc/yum.repos.d/ || exit $EXIT_UNEXPECTED;
if assert-system has-command dnf; then
    sudo dnf config-manager --add-repo /etc/yum.repos.d/resilio-sync.repo || exit $EXIT_UNEXPECTED;
    sudo dnf config-manager --set-enabled resilio-sync || exit $EXIT_UNEXPECTED;
fi

compose h1 "Installing Resilio Sync"
if assert-system has-command dnf; then
    sudo dnf install resilio-sync || exit $EXIT_UNEXPECTED
elif assert-system has-command rpm-ostree; then
    sudo rpm-ostree install resilio-sync || exit $EXIT_UNEXPECTED
else
    compose error "No installer for sync repository"
    exit $EXIT_UNEXPECTED
fi

compose h1 "Configuring Sync"
sudo cp $LIB_SRC_ROOT/rhel/resources/sync-server.json /etc/resilio-sync/config.json || exit $EXIT_UNEXPECTED;

if assert-system is-graphical; then
    sudo systemctl --user enable resilio-sync.service || exit $EXIT_UNEXPECTED
else
    sudo systemctl enable resilio-sync.service || exit $EXIT_UNEXPECTED
fi

if assert-system has-command dnf; then
    compose h2 "Starting Service"
    sudo systemctl start resilio-sync.service || exit $EXIT_UNEXPECTED
fi
 
compose success "Successfully installed Sync"
