#!/usr/bin/env bash

HOSTNAME=$(hostname)
KEYFILE=$SECURE_HOME/Certificates/$HOSTNAME.key
CERTFILE=$SECURE_HOME/Certificates/$HOSTNAME.crt
SYNC_HOME=/var/lib/resilio-sync
BIN_FILE=$SYNC_HOME/rslsync

function __status {
    systemctl status resilio-sync.service >/dev/null 2>&1 || exit 2
    if [ ! -f $BIN_FILE ]; then exit 2; fi
}

function __configure {
    if [ ! -f $CERTFILE ] || [ ! -f $KEYFILE ]; then
        mdf ">>> Script requires a cert+key pair uploaded to the home directory. Expected files at:"
        mdf " - $CERTFILE"
        mdf " - $KEYFILE"
        exit $EXIT_ILLEGAL_STATE
    fi
    if [ ! -f $BIN_FILE ]; then
        mdf ">>> Executable missing at: $BIN_FILE"
        exit $EXIT_ILLEGAL_STATE
    fi

    mdf "# Prepare service for Configure"
    sudo systemctl stop resilio-sync.service >/dev/null 2>&1
    sudo trash -f /etc/systemd/system/resilio-sync.service
    sudo cp $LIB_SRC_ROOT/rhel/resources/resilio-sync-server.service /etc/systemd/system/resilio-sync.service || exit $EXIT_UNEXPECTED

    mdf "# Configuring Sync Server"
    sudo cp $LIB_SRC_ROOT/rhel/resources/sync-server.json $SYNC_HOME/config.json || exit $EXIT_UNEXPECTED
    sudo mv $KEYFILE $SYNC_HOME || exit $EXIT_UNEXPECTED
    sudo mv $CERTFILE $SYNC_HOME || exit $EXIT_UNEXPECTED
    sudo useradd rslsync || exit $EXIT_UNEXPECTED
    sudo chown -R rslsync:rslsync $SYNC_HOME || exit $EXIT_UNEXPECTED

    mdf "# Configuring Firewall"
    sudo firewall-cmd --permanent --add-port=8888/tcp  || exit $EXIT_UNEXPECTED
    sudo firewall-cmd --permanent --add-port=34034/tcp  || exit $EXIT_UNEXPECTED
    sudo firewall-cmd --permanent --add-port=34034/udp  || exit $EXIT_UNEXPECTED
    sudo firewall-cmd --permanent --add-port=3838/udp  || exit $EXIT_UNEXPECTED
    sudo firewall-cmd --permanent --add-port=1900/udp  || exit $EXIT_UNEXPECTED
    sudo firewall-cmd --permanent --add-port=5351/udp  || exit $EXIT_UNEXPECTED
    sudo systemctl restart firewalld || exit $EXIT_UNEXPECTED

    mdf "# Starting Service"
    sudo systemctl enable resilio-sync.service || exit $EXIT_UNEXPECTED
    sudo systemctl start resilio-sync.service || exit $EXIT_UNEXPECTED

    mdf "+ Configured"
}

command=$1;
shift

case $command in
    "status")
        __status $@
    ;;
    "configure")
        __configure $@
    ;;
    *)
        exit $EXIT_ILLEGAL_ARG
    ;;
esac
