#!/usr/bin/env bash


function __status {
    systemctl --user is-enabled garbage-collect.service >/dev/null 2>&1 || exit 2
}

function __configure {
    mdf "> Copying service file"
    cp $LIB_SRC_ROOT/rhel/resources/garbage-collect.service $HOME/.config/systemd/user/
    mdf "> Enabling Service"
    systemctl --user enable garbage-collect.service || exit $EXIT_UNEXPECTED

    mdf "+ Configured"
}

command=$1;
shift

case $command in
    "status")
        __status $@
    ;;
    "configure")
        __configure $@
    ;;
    *)
        exit $EXIT_ILLEGAL_ARG
    ;;
esac
