#!/usr/bin/env bash

HOSTNAME=$(hostname)
KEYFILE=$SECURE_HOME/Certificates/$HOSTNAME.key
CERTFILE=$SECURE_HOME/Certificates/$HOSTNAME.crt

function __status {
    systemctl status resilio-sync.service >/dev/null 2>&1 || exit 2
}

function __configure {
    if [ ! -f $CERTFILE ] || [ ! -f $KEYFILE ]; then
        mdf ">>> Script requires a cert+key pair uploaded to the home directory. Expected files at:"
        mdf " - $CERTFILE"
        mdf " - $KEYFILE"
        exit $EXIT_ILLEGAL_ARG
    fi

    mdf "# Stopping Service for reconfigure"
    sudo systemctl stop resilio-sync.service || exit $EXIT_UNEXPECTED

    mdf "# Configuring Sync Server"
    sudo cp $LIB_SRC_ROOT/rhel/resources/sync-server.json /etc/resilio-sync/config.json || exit $EXIT_UNEXPECTED
    sudo mv $KEYFILE /var/lib/resilio-sync/ || exit $EXIT_UNEXPECTED
    sudo mv $CERTFILE /var/lib/resilio-sync/ || exit $EXIT_UNEXPECTED

    mdf "# Configuring Firewall"
    sudo firewall-cmd --permanent --add-port=8888/tcp  || exit $EXIT_UNEXPECTED
    sudo firewall-cmd --permanent --add-port=34034/tcp  || exit $EXIT_UNEXPECTED
    sudo firewall-cmd --permanent --add-port=34034/udp  || exit $EXIT_UNEXPECTED
    sudo firewall-cmd --permanent --add-port=3838/udp  || exit $EXIT_UNEXPECTED
    sudo firewall-cmd --permanent --add-port=1900/udp  || exit $EXIT_UNEXPECTED
    sudo firewall-cmd --permanent --add-port=5351/udp  || exit $EXIT_UNEXPECTED
    sudo service firewalld restart || exit $EXIT_UNEXPECTED

    mdf "# Starting Service"
    sudo systemctl enable resilio-sync.service || exit $EXIT_UNEXPECTED
    sudo systemctl start resilio-sync.service || exit $EXIT_UNEXPECTED

    mdf "+ Configured"
}

command=$1;
shift

case $command in
    "status")
        __status $@
    ;;
    "configure")
        __configure $@
    ;;
    *)
        exit $EXIT_ILLEGAL_ARG
    ;;
esac
