#!/usr/bin/env bash
WARD_HOME=$HOME/.ward;

if [ -z "$WARD_KEY" ]; then
    mdf ">>> Environment variable 'WARD_KEY' was not set.";
    exit $EXIT_ILLEGAL_STATE;
fi

COMMAND=$1;
shift;

function __assert-home-safety {
    if [[ $(stat -c "%a" $WARD_HOME) != "700" ]]; then
        mdf ">>> Illegal permissions on ward home. Please init or clean."
        exit $EXIT_ILLEGAL_STATE
    fi
}

function __encrypt {
    local FILE=$(echo $1 | sed 's:/*$::');
    shift;
    if [[ "$FILE" == "." ]]; then
        mdf ">>> Cannot close current directory"
        exit $EXIT_ILLEGAL_ARG;
    fi;

    if [[ -d "$FILE" ]]; then
        local TARBALL=${FILE}.tar.gz
        tar -czf ./$TARBALL ./$FILE || exit $EXIT_UNEXPECTED;
        rm -rf $FILE;
        __encrypt ./$TARBALL || exit $EXIT_UNEXPECTED;
    elif [[ -f "$FILE" ]]; then
        gpg --encrypt --armor -r $WARD_KEY $FILE || exit $EXIT_UNEXPECTED;
        rm $FILE;
        echo $FILE.asc;
    else
        mdf ">>> File not found: $FILE"
        exit $EXIT_ILLEGAL_ARG;
    fi
}

function __decrypt {
    FILE=$1;
    shift;
    if [ -z "$FILE" ]; then
        mdf ">>> File argument required."
        exit $EXIT_ILLEGAL_ARG;
    fi
    local DECRYPTED=$(echo $FILE | rev | cut -f 2- -d '.' | rev)
    gpg --decrypt $FILE > $DECRYPTED || exit $EXIT_UNEXPECTED;
    rm $FILE;

    if [[ $DECRYPTED == *.tar.gz ]]; then
        tar -xzf $DECRYPTED || exit $EXIT_UNEXPECTED;
        rm $DECRYPTED;
        echo ${DECRYPTED/.tar.gz/};
    else
        echo $DECRYPTED;
    fi
}

function __copy-prop {
    FILE=$1;
    shift;
    PROPERTY=$1
    shift;

    if [ -z "$FILE" ]; then
        mdf ">>> File argument required."
        exit $EXIT_ILLEGAL_ARG;
    fi

    if [ -z "$PROPERTY" ]; then
        mdf ">>> Property argument required."
        exit $EXIT_ILLEGAL_ARG;
    fi

    gpg --decrypt $FILE | grep "$PROPERTY" | cut -d'=' -f2 | clip
    mdf "+ Copied $FILE/$PROPERTY to clipboard"
    mdf "> Use within 30 seconds"
    $(sleep 30 && echo "" | clip) & 
}

function __prepareTmpFolder {
    mkdir -p $HOME/.ward/ || exit $EXIT_UNEXPECTED;
}

function __airlock {
    __assert-home-safety;
    __prepareTmpFolder;
    local FILE="";
    local SAVE=false;
    local AIRLOCK="$WARD_HOME/airlock-$RANDOM";

    while test $# -gt 0; do
        case "$1" in
            -s|--save)
                SAVE=true;
                shift;
                ;;
            *)
                FILE=$1;
                shift;
        esac
    done

    mkdir $AIRLOCK;

    cp $FILE $AIRLOCK;
    local START_DIR=$(pwd);
    local FILENAME=$(basename $FILE)
    cd $AIRLOCK;
        local DECRYPTED=$(__decrypt $FILENAME || (__shred $AIRLOCK; exit $EXIT_UNEXPECTED));
        mdf "----------"
        mdf "# Airlock for $FILENAME"
        mdf "To close, exit this shell."
        mdf "----------"
        ls -als
        mdf "----------"
        bash -l
        local STATUS=$?

        if [ $SAVE = true ] && [ $STATUS = 0 ]; then
            mdf "Saving Changes"
            __encrypt $DECRYPTED;
            cp -i $FILENAME $START_DIR/;
        fi
    cd -;

    __shred $AIRLOCK;
}

function __shred {
    local FILE=$1;
    
    if [[ "$FILE" == "" ]] || [[ "$FILE" == "/" ]] || [[ "$FILE" == "." ]]; then
        mdf ">>> Refusing to shred ambiguous directory"
        exit $EXIT_ILLEGAL_ARG;
    fi

    if [[ -d "$FILE" ]]; then
        find $FILE/ -type f -exec shred --remove {} \;;
        rm -r $FILE/;
    elif [[ -f "$FILE" ]]; then
        shred --remove $FILE;
    else
        mdf ">> Shred file not found: $FILE"
    fi
}

function __keymod {
    __assert-home-safety;
    __prepareTmpFolder;
    local KEYNAME=$1;
    local KEYCHAIN="pgp-keychain.tar.gz.asc";
    local KEY_PRIVATE=pgp-keychain/$KEYNAME-private.gpg;
    local KEY_PUBLIC=pgp-keychain/$KEYNAME-public.gpg;
    local SECURE_HOME=$HOME/Secure;
    local AIRLOCK="$WARD_HOME/airlock-$RANDOM";

    mkdir $AIRLOCK;
    cp $SECURE_HOME/$KEYCHAIN $AIRLOCK;

    cd $AIRLOCK;
        __decrypt $KEYCHAIN || (__shred $AIRLOCK; exit $EXIT_UNEXPECTED);
        if [[ ! -f "$KEY_PUBLIC" ]] || [[ ! -f "$KEY_PRIVATE" ]]; then
            mdf ">>> Key-pair for <$KEYNAME> not found";
            __shred $AIRLOCK;
            exit $EXIT_ILLEGAL_ARG;
        fi
        gpg --import $KEY_PUBLIC $KEY_PRIVATE;
        mdf "----------"
        mdf "# Editing $KEYNAME"
        mdf "To close, exit this shell."
        mdf "----------"
        bash -l;
        gpg --delete-secret-key $KEYNAME\!;
    cd -;

    __shred $AIRLOCK;
}

function __push-key {
    KEY=$1

    if [[ "$KEY" == "" ]]; then
        mdf ">>> Key argument missing"
        exit $EXIT_ILLEGAL_ARG
    fi

    mdf "# Sending key to keyservers"
    __push-key-keyserver $KEY keyserver.ubuntu.com
    __push-key-keyserver $KEY pgp.mit.edu
    __push-key-keyserver $KEY keys.openpgp.org
    mdf "++ Keys pushed"
}

function __push-key-keyserver {
    mdf " - Pushing to: $2"
    gpg --keyserver $2 --send-keys $1
}

function __init {
    mdf " - Initializing WARD_HOME at $WARD_HOME"
    mkdir -p $WARD_HOME;
    chmod 700 $WARD_HOME;
}

function __clean {
    mdf " - Shreding working directory"
    __shred $WARD_HOME
    __init
}

function __help {
    mdf "# Commands:"
    mdf "[airlock] [file] [--save] - Opens a file in a temporary directory that will be destroyed when closed."
    mdf "[clean] - Clean and re-initialize ward."
    mdf "[copy-prop] [file] [property] - Copy a property from an encrypted file"
    mdf "[decrypt] [file] - Decrypts a file."
    mdf "[encrypt] [file] - Encrypts a file."
    mdf "[init] - Initialize Ward configuration"
    mdf "[keymod] [key] - Temporarily imports a private key"
    mdf "[push-key] [key] - Pushes a key to PGP keyservers"
}

case $COMMAND in
    "help")
        __help;
        ;;
    "airlock")
        __airlock $@;
        ;;
    "clean")
        __clean $@;
        ;;
    "copy-prop")
        __copy-prop $@;
        ;;
    "decrypt")
        __decrypt $@;
        ;;
    "encrypt")
        __encrypt $@;
        ;;
    "init")
        __init $@;
        ;;
    "keymod")
        __keymod $@;
        ;; 
    "push-key")
        __push-key $@;
        ;;
    *)
        mdf ">>> Command '$COMMAND' not found";
        __help;
        exit $EXIT_ILLEGAL_ARG;
esac
