#!/usr/bin/env bash

REMOTE=$1
BRANCH=$2

if [[ "$REMOTE" == "" ]] || [[ "$BRANCH" == "" ]]; then
    mdf ">>> Usage: git-safe-pull REMOTE BRANCH"
    exit $EXIT_ILLEGAL_ARG
fi

git pull --ff-only --verify-signatures $REMOTE $BRANCH || exit $EXIT_UNEXPECTED
