#!/usr/bin/env bash

mdf "# Installing Core Dependencies"

if [[ "$OSTYPE" == "darwin"* ]]; then
    if ! assert-system has-command brew; then
        mdf "## Installing HomeBrew."
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
    fi

    if ! assert-system has-command brew; then
        mdf ">>> Installation Failed. Try https://brew.sh"
        exit $EXIT_UNEXPECTED;
    fi
fi

mdf "# Creating Directories"
mkdir -p $BIN_HOME

mdf "# Installing Libraries"

if assert-system has-command brew; then 
    mdf "## Installing Homebrew Packages"
    brew install $(tr '\r\n' ' ' < "$LIB_SRC_ROOT/macos/resources/packages-brew") || exit $EXIT_UNEXPECTED
fi

if assert-system has-command dnf; then
    mdf "## Updating DNF Packages"
    sudo dnf update || exit $EXIT_UNEXPECTED
    mdf "## Installing DNF Packages"
    sudo dnf install $(tr '\r\n' ' ' < "$LIB_SRC_ROOT/rhel/resources/packages-dnf") || exit $EXIT_UNEXPECTED
fi

if assert-system has-command rpm-ostree; then
    mdf "## Installing ostree updates"
    sudo rpm-ostree upgrade || $EXIT_UNEXPECTED
    mdf "## Installing ostree layers"
    sudo rpm-ostree install --idempotent $(tr '\r\n' ' ' < "$LIB_SRC_ROOT/rhel/resources/packages-ostree") || exit $EXIT_UNEXPECTED
    if [ ! -f $HOME/.config/lib-setup-rpm-ostree-complete ]; then
        mkdir -p $HOME/.config
        touch $HOME/.config/lib-setup-rpm-ostree-complete
        mdf "> Restart is required to continue Installation."
        mdf "> Re-Run installation script after restart"
        exit
    fi
fi

if assert-system is-graphical; then 
    if assert-system has-command snap; then
        mdf "## Installing Snap Packages"
        if [ ! -L /snap ]; then sudo ln -s /var/lib/snapd/snap /snap || exit $EXIT_UNEXPECTED; fi
        while read in; do 
            sudo snap install $in || exit $EXIT_UNEXPECTED
        done < $LIB_SRC_ROOT/linux/resources/packages-snap
        while read in; do 
            sudo snap install --classic $in || exit $EXIT_UNEXPECTED
        done < $LIB_SRC_ROOT/linux/resources/packages-snap-classic
    fi

    if assert-system has-command flatpak; then
        mdf "## Enabling Flathub"
        sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

        mdf "## Installing Flatpak Packages"
        while read in; do 
            flatpak install -y $in || exit $EXIT_UNEXPECTED
        done < $LIB_SRC_ROOT/linux/resources/packages-flatpak
    fi
fi

mdf "# Configuring"

mdf "## Linking configurations"
if assert-system os macos; then 
    re-link $$LIB_SRC_ROOT/macos/resources/.hyper.js $HOME/.hyper.js || exit $EXIT_UNEXPECTED
fi
if assert-system os linux && assert-system is-graphical; then
    re-link $LIB_SRC_ROOT/linux/resources/.hyper.js $HOME/.hyper.js || exit $EXIT_UNEXPECTED
fi
re-link $LIB_SRC_ROOT/common/resources/gitconfig $HOME/.gitconfig || exit $EXIT_UNEXPECTED
re-link $LIB_SRC_ROOT/common/resources/gitignore $HOME/.gitignore || exit $EXIT_UNEXPECTED
re-link $LIB_SRC_ROOT/common/resources/inputrc $HOME/.inputrc || exit $EXIT_UNEXPECTED

if assert-system os linux && assert-system is-graphical; then
    mdf "## Configuring gnome"
    configure-gnome || exit $EXIT_UNEXPECTED
fi

if assert-system os rhel; then
    mdf "## Configuring Systemd"

    mdf " - Create systemd User Directory"
    mkdir -p ~/.config/systemd/user/

    mdf " - Enabling Garbage Collection"
    cp $LIB_SRC_ROOT/rhel/resources/garbage-collect.service $HOME/.config/systemd/user/ || exit $EXIT_UNEXPECTED
    systemctl --user enable garbage-collect.service || exit $EXIT_UNEXPECTED

    mdf " - Enabling Bin Rotation"
    cp $LIB_SRC_ROOT/rhel/resources/rotate-bins.service $HOME/.config/systemd/user/ || exit $EXIT_UNEXPECTED
    systemctl --user enable rotate-bins.service || exit $EXIT_UNEXPECTED

    mdf " - Enabling App Rotation"
    cp $LIB_SRC_ROOT/rhel/resources/rotate-applications.service $HOME/.config/systemd/user/ || exit $EXIT_UNEXPECTED
    systemctl --user enable rotate-applications.service || exit $EXIT_UNEXPECTED
fi

mdf "++ Setup Complete"
